create table if not exists public.artifacts (
  id uuid primary key default gen_random_uuid(),
  serial_number integer generated by default as identity unique,
  slug text not null unique,
  artifact_name text not null,
  published_at timestamp with time zone null,
  demo_youtube_url text null,
  story_markdown text null,
  github_links jsonb not null default '[]'::jsonb,
  architecture_images jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint artifacts_github_links_array check (jsonb_typeof(github_links) = 'array'),
  constraint artifacts_architecture_images_array check (jsonb_typeof(architecture_images) = 'array')
);

-- Legacy columns from earlier iterations of this schema (problem/what-i-built/
-- architecture/implementation markdown, architecture components, data flow, LLM
-- used-for/not-used-for, code snippets, metrics, failure cases, tradeoffs, related
-- links, what-to-watch-for, build_date) were folded into `story_markdown` and
-- dropped. status/tagline/tools_libraries/demo_summary were dropped later still:
-- every artifact is now public from the moment it's created (no draft workflow),
-- and the title/story/images/video are the only content fields. Kept as explicit
-- drops so this file stays the source of truth for the live schema.
alter table public.artifacts
  drop constraint if exists artifacts_related_links_array,
  drop constraint if exists artifacts_architecture_components_array,
  drop constraint if exists artifacts_data_flow_array,
  drop constraint if exists artifacts_metrics_array,
  drop constraint if exists artifacts_failure_cases_array,
  drop constraint if exists artifacts_tradeoffs_array,
  drop constraint if exists artifacts_code_snippets_array,
  drop column if exists problem_markdown,
  drop column if exists what_i_built_markdown,
  drop column if exists architecture_markdown,
  drop column if exists implementation_markdown,
  drop column if exists architecture_components,
  drop column if exists data_flow,
  drop column if exists llm_used_for,
  drop column if exists llm_not_used_for,
  drop column if exists code_snippets,
  drop column if exists metrics,
  drop column if exists failure_cases,
  drop column if exists tradeoffs,
  drop column if exists related_links,
  drop column if exists build_date,
  drop column if exists what_to_watch_for,
  drop column if exists status,
  drop column if exists tagline,
  drop column if exists tools_libraries,
  drop column if exists demo_summary;

create index if not exists artifacts_public_listing_idx
  on public.artifacts (published_at desc nulls last, serial_number desc);

grant select on public.artifacts to anon, authenticated;
grant select, insert, update, delete on public.artifacts to service_role;

alter table public.artifacts enable row level security;

drop policy if exists "Artifacts are public when shipped or building." on public.artifacts;
drop policy if exists "Artifacts are public." on public.artifacts;
create policy "Artifacts are public."
  on public.artifacts
  for select
  to anon, authenticated
  using (true);

insert into storage.buckets (
  id,
  name,
  "public",
  file_size_limit,
  allowed_mime_types
)
values (
  'artifact-images',
  'artifact-images',
  true,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/svg+xml'
  ]
)
on conflict (id) do update set
  name = excluded.name,
  "public" = excluded."public",
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
