create table if not exists public.artifacts (
  id uuid primary key default gen_random_uuid(),
  serial_number integer generated by default as identity unique,
  slug text not null unique,
  artifact_name text not null,
  tagline text null,
  status text not null default 'draft',
  published_at timestamp with time zone null,
  demo_youtube_url text null,
  demo_summary text null,
  what_to_watch_for text[] not null default '{}'::text[],
  problem_markdown text null,
  what_i_built_markdown text null,
  architecture_markdown text null,
  implementation_markdown text null,
  github_links jsonb not null default '[]'::jsonb,
  related_links jsonb not null default '[]'::jsonb,
  architecture_images jsonb not null default '[]'::jsonb,
  architecture_components jsonb not null default '[]'::jsonb,
  data_flow jsonb not null default '[]'::jsonb,
  llm_used_for text[] not null default '{}'::text[],
  llm_not_used_for text[] not null default '{}'::text[],
  metrics jsonb not null default '[]'::jsonb,
  failure_cases jsonb not null default '[]'::jsonb,
  tradeoffs jsonb not null default '[]'::jsonb,
  code_snippets jsonb not null default '[]'::jsonb,
  tools_libraries text[] not null default '{}'::text[],
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint artifacts_status_check check (status in ('shipped', 'building', 'draft')),
  constraint artifacts_github_links_array check (jsonb_typeof(github_links) = 'array'),
  constraint artifacts_related_links_array check (jsonb_typeof(related_links) = 'array'),
  constraint artifacts_architecture_images_array check (jsonb_typeof(architecture_images) = 'array'),
  constraint artifacts_architecture_components_array check (jsonb_typeof(architecture_components) = 'array'),
  constraint artifacts_data_flow_array check (jsonb_typeof(data_flow) = 'array'),
  constraint artifacts_metrics_array check (jsonb_typeof(metrics) = 'array'),
  constraint artifacts_failure_cases_array check (jsonb_typeof(failure_cases) = 'array'),
  constraint artifacts_tradeoffs_array check (jsonb_typeof(tradeoffs) = 'array'),
  constraint artifacts_code_snippets_array check (jsonb_typeof(code_snippets) = 'array')
);

drop index if exists artifacts_public_listing_idx;

alter table public.artifacts
  drop column if exists build_date;

create index if not exists artifacts_public_listing_idx
  on public.artifacts (published_at desc nulls last, serial_number desc)
  where status in ('shipped', 'building');

create index if not exists artifacts_status_idx
  on public.artifacts (status);

create index if not exists artifacts_tools_libraries_idx
  on public.artifacts using gin (tools_libraries);

grant select on public.artifacts to anon, authenticated;
grant select, insert, update, delete on public.artifacts to service_role;

alter table public.artifacts enable row level security;

drop policy if exists "Artifacts are public when shipped or building." on public.artifacts;
create policy "Artifacts are public when shipped or building."
  on public.artifacts
  for select
  to anon, authenticated
  using (status in ('shipped', 'building'));

insert into storage.buckets (
  id,
  name,
  "public",
  file_size_limit,
  allowed_mime_types
)
values (
  'artifact-images',
  'artifact-images',
  true,
  10485760,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/svg+xml'
  ]
)
on conflict (id) do update set
  name = excluded.name,
  "public" = excluded."public",
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
